name: Run MegaBobs Fetcher Weekly

on:
  schedule:
    - cron: "0 16 * * 3" # 매주 목요일 오전 9시 (KST 기준)
  workflow_dispatch: # 수동 실행 버튼도 추가됨

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: pnpm install
      - name: Run fetcher
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node index.js
